pipeline:
  build:
    image: node:boron
    commands:
      - npm install
    when:
      branch: master
      event: push

  publish:
    image: plugins/docker
    registry: docker.soapbubble.online:5000
    repo: docker.soapbubble.online:5000/soapbubble/auth
    tag: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push
